In [8]:
import pandas as pd
url = "https://raw.githubusercontent.com/Oldmage112/TI4-Project/refs/heads/main/PowerBI/Derived%20CSVs/Data%20Science%20Project.csv"
df = pd.read_csv(url, low_memory=False, index_col= -1)

In [9]:
df

,Points,Expansions,PlayerCount,Platform,factionsInGame.1,factionsInGame.2,factionsInGame.3,factionsInGame.4,factionsInGame.5,factionsInGame.6,factionsInGame.7,factionsInGame.8,WinningFaction
Index,,,,,,,,,,,,,
396,10,Prophecy of Kings Only,6,Async,Sardakk N'orr,Emirates of Hacan,Universities of Jol-Nar,Xxcha Kingdom,Argent Flight,Vuil'raith Cabal,NaN,NaN,Xxcha Kingdom
600,10,Prophecy of Kings Only,6,Async,Naaz-Rokha Alliance,Mahact Gene-Sorcerers,Emirates of Hacan,Yin Brotherhood,Keleres ~ Mentak,Vuil'raith Cabal,NaN,NaN,Keleres ~ Mentak
831,10,Prophecy of Kings Only,6,Async,Yssaril Tribes,Naaz-Rokha Alliance,Argent Flight,Titans of Ul,Naalu Collective,Vuil'raith Cabal,NaN,NaN,Yssaril Tribes
3184,10,Prophecy of Kings Only,6,Async,Winnu,Universities of Jol-Nar,Barony of Letnev,Titans of Ul,Argent Flight,Vuil'raith Cabal,NaN,NaN,Argent Flight
3252,10,Prophecy of Kings Only,6,Async,Federation of Sol,Xxcha Kingdom,Yin Brotherhood,Argent Flight,Naaz-Rokha Alliance,Vuil'raith Cabal,NaN,NaN,Vuil'raith Cabal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13050,14,Prophecy of Kings Only,8,Async,Ghosts of Creuss,Arborec,Mahact Gene-Sorcerers,Emirates of Hacan,Empyrean,Nekro Virus,Argent Flight,Nomad,Empyrean
14050,14,Prophecy of Kings Only,8,Async,Federation of Sol,Clan of Saar,Universities of Jol-Nar,Winnu,L1Z1X Mindnet,Sardakk N'orr,Naalu Collective,Argent Flight,Winnu
14170,14,Prophecy of Kings Only,8,Async,Embers of Muaat,Xxcha Kingdom,Nomad,Mentak Coalition,Clan of Saar,Nekro Virus,Naaz-Rokha Alliance,Mahact Gene-Sorcerers,Mahact Gene-Sorcerers
14280,14,Prophecy of Kings Only,8,Async,Yssaril Tribes,Naalu Collective,Vuil'raith Cabal,Argent Flight,Xxcha Kingdom,Nomad,Clan of Saar,Mahact Gene-Sorcerers,Mahact Gene-Sorcerers
14358,14,Prophecy of Kings Only,8,Async,Ghosts of Creuss,Mahact Gene-Sorcerers,Universities of Jol-Nar,Argent Flight,L1Z1X Mindnet,Vuil'raith Cabal,Xxcha Kingdom,Winnu,Mahact Gene-Sorcerers

In [10]:
for column in df.columns[4:]:
    df[column] = df[column].str.replace('Il No Viroset', 'Il Na Viroset', regex=False)    
    for letter in ('The ','(',')','-','~','Council',' '):
        df[column] = df[column].str.replace(letter, '', regex=False)

In [30]:
df.columns
feeder = df.iloc[:,:-1]
winners = df.iloc[:,-1]
feeder
winners

Index
396             XxchaKingdom
600            KeleresMentak
831            YssarilTribes
3184            ArgentFlight
3252         Vuil'raithCabal
                ...
13050               Empyrean
14050                  Winnu
14170    MahactGeneSorcerers
14280    MahactGeneSorcerers
14358    MahactGeneSorcerers
Name: WinningFaction, Length: 17797, dtype: str

In [34]:
dummies = pd.get_dummies(feeder, columns=['factionsInGame.1',
       'factionsInGame.2', 'factionsInGame.3', 'factionsInGame.4',
       'factionsInGame.5', 'factionsInGame.6', 'factionsInGame.7',
       'factionsInGame.8'], prefix='', prefix_sep='')
final_dummies = dummies.iloc[:,1:].T.groupby(level=0).sum().T
final = pd.merge(dummies.iloc[:,0:4], final_dummies, left_index=True, right_index=True)
final = final.rename(columns= {'ASickeningLurch': 'A Sickening Lurch', 
                       'ArgentFlight' : 'Argent Flight',
                        'AvariceRex' : 'Avarice Rex', 
                        'BaronyofLetnev' : 'Barony of Letnev', 
                        'ClanofSaar' : 'Clan of Saar',
                        'KeleresArgent' : 'Keleres Argent', 
                        'KeleresMentak': 'Keleres Mentak', 
                        'KeleresXxcha': 'Keleres Xxcha',
                        'CrimsonRebellion' : 'Crimson Rebellion', 
                        'DeepwroughtScholarate' : 'Deepwrought Scholarate', 
                        'ElNenJanovet' : 'El Nen Janovet',
                        'EmbersofMuaat' : 'Embers of Muaat', 
                        'EmiratesofHacan': 'Emirates of Hacan', 
                        'FederationofSol' : 'Federation of Sol',
                        'GhostsofCreuss' : 'Ghosts of Creuss', 
                        'IlNaViroset' : 'Il Na Viroset',
                        'IlSaiLakoeHeraldofThorns' : 'Il Sai Lakoe, Herald of Thorns',
                        'L1Z1XMindnet': 'L1Z1X Mindnet', 
                        'LastBastion' : 'Last Bastion', 
                        'MahactGeneSorcerers' : 'Mahact Gene-Sorcerers',
                        'MentakCoalition': 'Mentak Coalition', 
                        'NaaluCollective' : 'Naalu Collective', 
                        'NaazRokhaAlliance':'Naaz-Rokha Alliance', 
                        'NekroVirus': 'Nekro Virus', 
                        'RadiantAur': 'Radiant Aur', 
                        'RalNelConsortium': 'Ral Nel Consortium', 
                        'RubyMonarch': 'Ruby Monarch',
                        'SaintofSwords' : 'Saint of Swords', 
                        "SardakkN'orr":"Sardakk N'orr", 
                        'TitansofUl':'Titans of Ul', 
                        'UniversitiesofJolNar':'Universities of Jol-Nar',
                        "Vuil'raithCabal" : "Vuil'raith Cabal", 
                        'XxchaKingdom' : 'Xxcha Kingdom', 
                        'YinBrotherhood': 'Yin Brotherhood',
                        'YssarilTribes': 'Yssaril Tribes',
                        'Expansions_x' : 'Expansions',	
                        'PlayerCount_x' : 'PlayerCount',	
                        'Platform_x': 'Platform'})
final.to_csv("C:\GitHub\TI4-Project\PowerBI\Derived CSVs\Factions_Transform.csv")
winners.to_csv("C:\GitHub\TI4-Project\PowerBI\Derived CSVs\Factions_Winners.csv")

In [33]:
final

,Points,Expansions,PlayerCount,Platform,A Sickening Lurch,Arborec,Argent Flight,Avarice Rex,Barony of Letnev,Clan of Saar,...,Ruby Monarch,Saint of Swords,Sardakk N'orr,Titans of Ul,Universities of Jol-Nar,Vuil'raith Cabal,Winnu,Xxcha Kingdom,Yin Brotherhood,Yssaril Tribes
Index,,,,,,,,,,,,,,,,,,,,,
396,10,Prophecy of Kings Only,6,Async,0,0,1,0,0,0,...,0,0,1,0,1,1,0,1,0,0
600,10,Prophecy of Kings Only,6,Async,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
831,10,Prophecy of Kings Only,6,Async,0,0,1,0,0,0,...,0,0,0,1,0,1,0,0,0,1
3184,10,Prophecy of Kings Only,6,Async,0,0,1,0,1,0,...,0,0,0,1,1,1,1,0,0,0
3252,10,Prophecy of Kings Only,6,Async,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13050,14,Prophecy of Kings Only,8,Async,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14050,14,Prophecy of Kings Only,8,Async,0,0,1,0,0,1,...,0,0,1,0,1,0,1,0,0,0
14170,14,Prophecy of Kings Only,8,Async,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
14280,14,Prophecy of Kings Only,8,Async,0,0,1,0,0,1,...,0,0,0,0,0,1,0,1,0,1
14358,14,Prophecy of Kings Only,8,Async,0,0,1,0,0,0,...,0,0,0,0,1,1,1,1,0,0