In [2]:
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/Oldmage112/TI4-Project/refs/heads/main/PowerBI/Derived%20CSVs/Objectives.csv'
df = pd.read_csv(url, low_memory=False, index_col= 0)
df.columns

Index(['Public_Objectives_I', 'Public_Objectives_II', 'PO1.1', 'PO1.2',
       'PO1.3', 'PO1.4', 'PO1.5', 'PO1.6', 'PO1.7', 'PO1.8', 'PO1.9', 'PO1.10',
       'PO1.11', 'PO1.12', 'PO1.13', 'PO1.14', 'PO1.15', 'PO1.16', 'PO1.17',
       'PO1.18', 'PO1.19', 'PO1.20', 'PO2.1', 'PO2.2', 'PO2.3', 'PO2.4',
       'PO2.5', 'PO2.6', 'PO2.7', 'PO2.8', 'PO2.9', 'PO2.10', 'PO2.11',
       'PO2.12', 'PO2.13', 'PO2.14', 'PO2.15', 'PO2.16', 'PO2.17', 'PO2.18',
       'PO2.19', 'PO2.20'],
      dtype='str')

In [15]:
df

,Public_Objectives_I,Public_Objectives_II,PO1.1,PO1.2,PO1.3,PO1.4,PO1.5,PO1.6,PO1.7,PO1.8,...,PO2.11,PO2.12,PO2.13,PO2.14,PO2.15,PO2.16,PO2.17,PO2.18,PO2.19,PO2.20
Index,,,,,,,,,,,,,,,,,,,,,
1,"['Engineer a Marvel', 'Intimidate Council', 'C...",[],Engineer a Marvel,Intimidate Council,Corner the Market,Discover Lost Outposts,Push Boundaries,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"['Develop Weaponry', 'Raise a Fleet', 'Make Hi...",[],Develop Weaponry,Raise a Fleet,Make History,Negotiate Trade Routes,Lead From the Front,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"['Negotiate Trade Routes', 'Populate the Outer...",[],Negotiate Trade Routes,Populate the Outer Rim,Make History,Raise a Fleet,Corner the Market,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"['Sway the Council', 'Lead From the Front', 'D...",[],Sway the Council,Lead From the Front,Develop Weaponry,Discover Lost Outposts,Negotiate Trade Routes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"['Intimidate Council', 'Populate the Outer Rim...",[],Intimidate Council,Populate the Outer Rim,Expand Borders,Improve Infrastructure,Lead From the Front,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17963,"['Push Boundaries', 'Raise a Fleet', 'Develop ...",['Master the Sciences'],Push Boundaries,Raise a Fleet,Develop Weaponry,Negotiate Trade Routes,Amass Wealth,Populate the Outer Rim,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17991,"['Populate the Outer Rim', 'Build Defenses', '...",['Unify the Colonies'],Populate the Outer Rim,Build Defenses,Erect a Monument,Found Research Outposts,Intimidate Council,Corner the Market,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18024,"['Lead From the Front', 'Improve Infrastructur...",['Form Galactic Brain Trust'],Lead From the Front,Improve Infrastructure,Erect a Monument,Expand Borders,Engineer a Marvel,Push Boundaries,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18084,"['Push Boundaries', 'Develop Weaponry', 'Explo...",['Galvanize the People'],Push Boundaries,Develop Weaponry,Explore Deep Space,Populate the Outer Rim,Amass Wealth,Erect a Monument,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18100,"['Make History', 'Engineer a Marvel', 'Expand ...",NaN,Make History,Engineer a Marvel,Expand Borders,Discover Lost Outposts,Found Research Outposts,Diversify Research,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
for column in df.columns:
    df[column] = df[column].str.replace('*', '', regex=False)

In [9]:
dummies = pd.get_dummies(df, columns=['PO1.1',
       'PO1.2', 'PO1.3', 'PO1.4', 'PO1.5', 'PO1.6', 'PO1.7', 'PO1.8', 'PO1.9',
       'PO1.10', 'PO1.11', 'PO1.12', 'PO1.13', 'PO1.14', 'PO1.15', 'PO1.16',
       'PO1.17', 'PO1.18', 'PO1.19', 'PO1.20', 'PO2.1', 'PO2.2', 'PO2.3',
       'PO2.4', 'PO2.5', 'PO2.6', 'PO2.7', 'PO2.8', 'PO2.9', 'PO2.10',
       'PO2.11', 'PO2.12', 'PO2.13', 'PO2.14', 'PO2.15', 'PO2.16', 'PO2.17',
       'PO2.18', 'PO2.19', 'PO2.20'], prefix='', prefix_sep='')
final_dummies = dummies.iloc[:,2:].T.groupby(level=0).sum().T
final = pd.merge(dummies.iloc[:,0:2], final_dummies, left_index=True, right_index=True)
final.to_csv("C:\GitHub\TI4 Project\PowerBI\Derived CSVs\Objectives_Transform.csv")

In [16]:
final_dummies

,Achieve Supremacy,Amass Wealth,Become a Legend,Build Defenses,Centralize Galactic Trade,Command an Armada,Conquer the Weak,Construct Massive Cities,Control Ordinian,Control the Borderlands,...,Revolutionize Warfare,Rule Distant Lands,Seize an Icon,Spark a Rebellion,Stake Your Claim,Strengthen Bonds,Subdue the Galaxy,Sway the Council,Threaten Enemies,Unify the Colonies
Index,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17963,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17991,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18024,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18084,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0