In [3]:
import pandas as pd

In [4]:
url = 'https://raw.githubusercontent.com/Oldmage112/TI4-Project/refs/heads/main/PowerBI/Derived%20CSVs/Technologies.csv'
df = pd.read_csv(url, low_memory=False, index_col= -1)
df = df.fillna('')

In [5]:
df

,technologies,Techs.1,Techs.2,Techs.3,Techs.4,Techs.5,Techs.6,Techs.7,Techs.8,Techs.9,Techs.10,Techs.11,Techs.12,Techs.13,Techs.14,Techs.15,Techs.16,Techs.17,Techs.18
Index,,,,,,,,,,,,,,,,,,,
290,"[""Sarween Tools"",""Yin Spinner Omega""]",Sarween Tools,Yin Spinner Omega,,,,,,,,,,,,,,,,
464,[],,,,,,,,,,,,,,,,,,
625,"[""Antimass Deflectors"",""Gravity Drive""]",Antimass Deflectors,Gravity Drive,,,,,,,,,,,,,,,,
783,"[""Magen Defense Grid ΩΩ""]",Magen Defense Grid ΩΩ,,,,,,,,,,,,,,,,,
784,"[""Dark Energy Tap""]",Dark Energy Tap,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94360,"[""Dacxive Animators"",""Valefar Assimilator X"",""...",Dacxive Animators,Valefar Assimilator X,Valefar Assimilator Y,Gravity Drive,Dark Energy Tap,Fighter II,Dimensional Tear II,Self Assembly Routines,Exotrireme II,Valkyrie Particle Weave,Assault Cannon,Duranium Armor,Scanlink Drone Network,Plasma Scoring,Fleet Logistics,Antimass Deflectors,Magen Defense Grid,
94412,"[""Dacxive Animators"",""Valefar Assimilator X"",""...",Dacxive Animators,Valefar Assimilator X,Valefar Assimilator Y,Gravity Drive,Hyper Metabolism,Dreadnought II,Sling Relay,Saturn Engine II,Neural Motivator,Light-Wave Deflector,Fleet Logistics,Assault Cannon,Antimass Deflectors,Dark Energy Tap,Sarween Tools,Plasma Scoring,Transit Diodes,Bio-Stims
94428,"[""Dacxive Animators"",""Valefar Assimilator X"",""...",Dacxive Animators,Valefar Assimilator X,Valefar Assimilator Y,Saturn Engine II,Gravity Drive,Assault Cannon,Non-Euclidean Shielding,Sling Relay,Antimass Deflectors,Infantry II,AI Development Algorithm,Light-Wave Deflector,Transit Diodes,Duranium Armor,Plasma Scoring,Scanlink Drone Network,PDS II,
94476,"[""Dacxive Animators"",""Valefar Assimilator X"",""...",Dacxive Animators,Valefar Assimilator X,Valefar Assimilator Y,Gravity Drive,Hyper Metabolism,Saturn Engine II,Antimass Deflectors,Sling Relay,Sarween Tools,Light-Wave Deflector,Carrier II,Neural Motivator,Fighter II,Assault Cannon,Transit Diodes,Scanlink Drone Network,Plasma Scoring,Integrated Economy
94587,"[""Dacxive Animators"",""Valefar Assimilator X"",""...",Dacxive Animators,Valefar Assimilator X,Valefar Assimilator Y,Antimass Deflectors,Strike Wing Alpha II,Gravity Drive,Carrier II,Yin Spinner,Dreadnought II,Dark Energy Tap,X-89 Bacterial Weapon,Bio-Stims,Fleet Logistics,Scanlink Drone Network,Fighter II,Predictive Intelligence,Sarween Tools,Prototype War Sun II

In [7]:
dummies = pd.get_dummies(df, columns=['Techs.1', 'Techs.2', 'Techs.3', 'Techs.4', 'Techs.5',
       'Techs.6', 'Techs.7', 'Techs.8', 'Techs.9', 'Techs.10', 'Techs.11',
       'Techs.12', 'Techs.13', 'Techs.14', 'Techs.15', 'Techs.16', 'Techs.17',
       'Techs.18'], prefix='', prefix_sep='')
final_dummies = dummies.iloc[:,1:].T.groupby(level=0).sum().T
final = pd.merge(dummies.iloc[:,0:1], final_dummies, left_index=True, right_index=True)
final_dummies.to_csv("C:\GitHub\TI4-Project\PowerBI\Derived CSVs\Technologies_Transform.csv")

In [8]:
final_dummies

,,001,4X41C Helios V2,4X41C \Helios\ V2,????_REDACTED_????,???\\_ERROR\\_ERROR\\_???,???\\_NULL\\_REFERENCE\\_???,???_EXCEPTION_NO_ID_???,?양함 II,?쟁 태양,...,wormhole_generator,x89_bacterial_weapon,x89_bacterial_weapon.codex4,yin_spinner,ysia_yssrila,구축함 II,드래드노트 II,보병 II,우주 항만 II,항공모함 II
Index,,,,,,,,,,,,,,,,,,,,,
290,16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
464,18,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
625,16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
783,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
784,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94360,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94412,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94428,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94476,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0